### ISSUE TITLE
Response filtering

### ISSUE THREAD

**Issue by ibragimov4xxi** [trusche/httplog#32]
Is there a way to filter the responce data (lambda/block)?
I want to filter the special data before sending it to the log.

**Comment by trusche** [comment]
There isn't, I'm afraid. Could you describe your use case in a bit more detail?

**Comment by ibragimov4xxi** [comment]
Yes. I have some secret data in response (on my projcet), and i want to filter this data because i do not want to save some specific private info (secret tokens, bank acmount, user's bank accounts, any other).

**Comment by trusche** [comment]
Sorry, not supported atm. And I would strongly recommend against using this in production anyway. This gem messes with the network stack, so although I'm not aware of any, there are no guarantees of zero side effects. For your use case, I would recommend to capture, filter and then store the response from any API calls explicitly, instead of relying on HTTP request logging.
