### ISSUE TITLE
How do I turn off logging?

### ISSUE THREAD

**Issue by noorani786** [trusche/httplog#35]
I don't want to remove the gem from the Gemfile but want to turn off http logging temporarily. How do I do that?

Thanks!

**Comment by trusche** [comment]
@noorani786 There's currently no way to do that. You have two options: a) Set `HttpLog.options[:compact_log]   = true` to greatly reduce the amount of logging, or b) comment out the gem in the Gemfile and `bundle` (and comment out any configuration as well). Since this is only a development tool, that shouldn't be much of an effort. You could also try to set `HttpLog.options[:url_blacklist_pattern] = /.*/` - I'm actually not sure if that will completely suppress all output.
