### ISSUE TITLE
Double content-type header handled incorrectly

### ISSUE THREAD

**Issue by nicktime** [trusche/httplog#62]
```> GET /52/528afcb3-4f2f-4f10-b712-4c41904eda56.pdf HTTP/1.1
> Host: localhost:2080
> User-Agent: curl/7.47.0
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: DAV/0.9.11 Python/3.5.2
< Date: Wed, 26 Sep 2018 08:44:24 GMT
< Content-type: application/pdf
< Transfer-Encoding: chunked
< Date: Wed, 26 Sep 2018 08:44:24 GMT
< DAV: 1,2
< Keep-Alive: timeout=15, max=86
< Last-Modified: Tue, 28 Aug 2018 13:10:16 GMT
* HTTP/1.0 connection set to keep alive!
< Connection: Keep-Alive
< Content-Length: 17896
< Content-Type: application/pdf
< 
```
In this case HTTP gem provides Content-Type as an array and `text_based?` handles it incorrectly.

**Comment by nicktime** [comment]
That was PyWebDAV3 I don't know though how widespread this problem is.

**Comment by trusche** [comment]
Based on [this](https://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable) and a closer look at the RFC, I'd suggest this is an invalid HTTP response and as such shouldn't be explicitly handled by httplog. We *could* ensure that Arrays of content types are accommodated (e.g. take the last value in that case), but this seems to be such a specific issue that I'd rather not bother since it incurs a cost (in terms of code complexity and additional method calls), although not a high one. 

Thoughts?

**Comment by nicktime** [comment]
That's fine. Standards a rarely strictly complied to though.
