### ISSUE TITLE
Support for production?

### ISSUE THREAD

**Issue by n-rodriguez** [trusche/httplog#75]
It could be nice to be able to run it where it's most useful : in production.
If you have an issue with an external API but can't log it from your application (with a feature switch or whatever) the usage is very reduce.

my 2 cents.

**Comment by trusche** [comment]
Hi @n-rodriguez! There's really nothing stopping you from running this in production. I'm just pretty explicit in warning against it since this gem is basically a collection of monkey patches that mess with pretty low-level stuff. 

I'd suggest that if you have an issue with an API cropping up in production, your first stop would be trying to reproduce it in your development or staging environment. If that's really not an option, you can of course ignore my warnings and use this in production, there's nothing preventing you from doing so. I'm not *aware* of any issues that might affect production, but you've been warned just in case 😄
