### ISSUE TITLE
HTTP gem does not work with this gem

### ISSUE THREAD

**Issue by kapso** [trusche/httplog#89]
When I enable this gem, the HTTP [gem](https://github.com/httprb/http) does not return any data. So basically the following request returns an empty response.

`content = HTTP.get(URL).body.to_s`

Versions I am using -

```ruby
ruby '2.7.0'
gem 'httplog', '1.4.0'
gem 'rails', '6.0.2.1'
gem 'http', '4.3.0'
```

**Comment by trusche** [comment]
Well that's not good... :) Checking now

**Comment by trusche** [comment]
Well, it works fine with ruby 2.6.5 for me. With this setup:

```
# Gemfile
source 'https://rubygems.org'
ruby '2.6.5'

gem 'http'
gem 'httplog', '1.4.0'
```

```
# test.rb
require 'http'
require 'httplog'

puts HTTP.get('http://example.com').body.to_s
```

running `bundle exec test.rb` spits out the content of example.com. Checking ruby 2.7 now...

**Comment by trusche** [comment]
Works the same for me with ruby 2.7.0. http gem version is 4.3.0 - which one do you have? And can you provide a minimum example that reproduces the issue?

**Comment by kapso** [comment]
I am using `gem 'http', '4.3.0'`

**Comment by maximeg** [comment]
I did stumble on that on one personal project (and hopefully, we weren't affected at work due to binary only responses).

 I was going to make a PR for that this morning.

The culprit is the new added `.dup` in `HttpLog#log_body`:

```ruby
data = parse_body(body.dup, mask_body, encoding, content_type)
```

With that, you have two instances of `HTTP::Response`. The first one to be "read" (by using `to_s`) will consume the response from the connection. The other to be read will get nothing.

If the content type is "loggable", the instance in httplog is read and the instance you get is empty. If binary (hence not "loggable"), that's the response you get.

A proper way is:
- not dup here, but in parsse_body if needed
- call to_s explicitly before that instead of relying on the implicit to_s of the string interpolation.

**Comment by kapso** [comment]
Thanks, @maximeg 

Curious when this fix will be released?
